set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 10)

if(NOT LLVM_MINGW_ROOT AND DEFINED ENV{LLVM_MINGW_ROOT})
    set(LLVM_MINGW_ROOT "$ENV{LLVM_MINGW_ROOT}")
endif()

if(NOT DEFINED LLVM_MINGW_ROOT)
    message(FATAL_ERROR "LLVM_MINGW_ROOT is not set. Run the Windows build script so it can provision the toolchain automatically.")
endif()

file(TO_CMAKE_PATH "${LLVM_MINGW_ROOT}" LLVM_MINGW_ROOT_NORMALIZED)
set(LLVM_MINGW_ROOT "${LLVM_MINGW_ROOT_NORMALIZED}" CACHE PATH "LLVM MinGW toolchain root" FORCE)
set(LLVM_MINGW_TRIPLE "x86_64-w64-mingw32")
set(LLVM_MINGW_BIN "${LLVM_MINGW_ROOT_NORMALIZED}/bin")

set(CMAKE_C_COMPILER "${LLVM_MINGW_BIN}/${LLVM_MINGW_TRIPLE}-clang.exe")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW_BIN}/${LLVM_MINGW_TRIPLE}-clang++.exe")
set(CMAKE_RC_COMPILER "${LLVM_MINGW_BIN}/${LLVM_MINGW_TRIPLE}-windres.exe")
set(CMAKE_AR "${LLVM_MINGW_BIN}/${LLVM_MINGW_TRIPLE}-ar.exe")
set(CMAKE_RANLIB "${LLVM_MINGW_BIN}/${LLVM_MINGW_TRIPLE}-ranlib.exe")

set(CMAKE_C_COMPILER_TARGET "${LLVM_MINGW_TRIPLE}")
set(CMAKE_CXX_COMPILER_TARGET "${LLVM_MINGW_TRIPLE}")
